addSbtPlugin("de.heikoseeberger" % "sbt-header"         % "5.7.0")
addSbtPlugin("com.github.sbt"    % "sbt-release"        % "1.1.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"      % "2.0.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"       % "2.4.6")
addSbtPlugin("ch.epfl.scala"     % "sbt-version-policy" % "2.0.1")
